pipeline_setup:

  pipeline_name: cpac-default

  output_directory:
    path: /home/arunav/Assets/ADHD-200/PaloAlto-outputs/
    pull_source_once: True
    write_func_outputs: False
    write_debugging_outputs: False
    output_tree: "default"

    quality_control:
      generate_quality_control_images: True
      generate_xcpqc_files: False

  working_directory:
    path: /home/arunav/Assets/ADHD-200/PaloAlto-outputs/working
    remove_working_dir: True

  log_directory:
    run_logging: True
    path: /home/arunav/Assets/ADHD-200/PaloAlto-outputs/logging

  crash_log_directory:
    path: /home/arunav/Assets/ADHD-200/PaloAlto-outputs/crash

  system_config:
    maximum_memory_per_participant: 1
    raise_insufficient: On
    observed_usage:
      buffer: 10
    max_cores_per_participant: 1
    num_ants_threads: 1
    num_OMP_threads: 1
    num_participants_at_once: 1
    FSLDIR:  /usr/local/fsl

  Debugging:
    verbose: On
